-- Insert sample roles
INSERT INTO ROLE (id, name, title, created_by, role_type) VALUES
(1, 'Admin', 'System Administrator', 'System', 'SUPER_ADMIN'),
(2, 'Manager', 'Operations Manager', 'HR', 'MANAGER'),
(3, 'Developer', 'Software Engineer', 'TechLead', 'ENGINEER'),
(4, 'Analyst', 'Business Analyst', 'CEO', 'ANALYST'),
(5, 'Tester', 'QA Tester', 'QA Lead', 'TESTER'),
(6, 'Support', 'Customer Support', 'SupportManager', 'SUPPORT'),
(7, 'HR', 'Human Resources', 'HR Head', 'HR'),
(8, 'Finance', 'Finance Manager', 'CFO', 'FINANCE'),
(9, 'Security', 'Security Officer', 'SecurityLead', 'SECURITY'),
(10, 'Marketing', 'Marketing Executive', 'MarketingHead', 'MARKETING'),
(11, 'Admin Assistant', 'Assistant to Admin', 'Admin', 'ASSISTANT'),
(12, 'Sales', 'Sales Executive', 'SalesHead', 'SALES'),
(13, 'Product Manager', 'Product Lead', 'CEO', 'PRODUCT_MANAGER'),
(14, 'UX Designer', 'User Experience Designer', 'DesignHead', 'DESIGNER'),
(15, 'DevOps', 'DevOps Engineer', 'TechOps', 'DEVOPS'),
(16, 'Database Admin', 'Database Administrator', 'DBA', 'DBA'),
(17, 'Data Scientist', 'AI & Data Science', 'AI Head', 'DATA_SCIENTIST'),
(18, 'Research', 'Research Engineer', 'ResearchHead', 'RESEARCH'),
(19, 'Legal', 'Legal Advisor', 'LegalHead', 'LEGAL'),
(20, 'Content Creator', 'Media & Content', 'MarketingHead', 'CONTENT_CREATOR');

-- Insert sample resources
INSERT INTO RESOURCE (id, name, title, created_by, resource_type) VALUES
(1, 'Server1', 'Production Server', 'Admin', 'COMPUTE'),
(2, 'Database1', 'Primary DB', 'Admin', 'STORAGE'),
(3, 'API Gateway', 'Internal API Gateway', 'DevOps', 'NETWORKING'),
(4, 'Backup Server', 'Disaster Recovery', 'Admin', 'COMPUTE'),
(5, 'Firewall', 'Security Firewall', 'Security', 'SECURITY'),
(6, 'Analytics Server', 'BI Reporting', 'Data Scientist', 'COMPUTE'),
(7, 'Load Balancer', 'Traffic Management', 'Networking', 'NETWORKING'),
(8, 'Mainframe', 'Legacy System', 'IT Support', 'COMPUTE'),
(9, 'Cloud Storage', 'AWS S3', 'CloudOps', 'STORAGE'),
(10, 'CI/CD Pipeline', 'Deployment System', 'DevOps', 'TOOLING'),
(11, 'Chatbot Server', 'Customer Support Bot', 'AI Team', 'COMPUTE'),
(12, 'Marketing DB', 'Customer Data Storage', 'Marketing', 'STORAGE'),
(13, 'Finance Ledger', 'Accounting System', 'Finance', 'STORAGE'),
(14, 'Sales CRM', 'Customer Relationship Management', 'Sales', 'SOFTWARE'),
(15, 'HRMS', 'Human Resource Management System', 'HR', 'SOFTWARE'),
(16, 'Project Tracker', 'Agile Management', 'PMO', 'SOFTWARE'),
(17, 'Git Repository', 'Source Code Management', 'Developers', 'TOOLING'),
(18, 'Billing System', 'Invoicing & Payment', 'Finance', 'SOFTWARE'),
(19, 'Inventory System', 'Stock Management', 'Operations', 'SOFTWARE'),
(20, 'Email Server', 'Enterprise Email Service', 'IT Admin', 'COMMUNICATION');
